### PR TITLE
Wykonywanie migracji tylko jak dodano nowe.

### PR DESCRIPTION
**Pull request by d0minikk**
:>

### CODE REVIEW

**Comment by madsheep** [comment]
seems quite hacky and not really tested. What are the benefits of this approach?

**Comment by d0minikk** [comment]
about 20 seconds faster dep without migrations

**Comment by madsheep** [comment]
Tested with your project? Still lacks tests.

**Comment by d0minikk** [comment]
ouch not hereeeee

**Comment by mamut** [comment]
Not worth the 20 seconds boost.

**Pull request closed without merging**
