### PR TITLE
Spec speedup generator

### PR DESCRIPTION
**Pull request by mamut**
Work in progress (some more stuff will be added) but I appreciate any comments.

### CODE REVIEW

**Comment by mamut** [comment]
Stuff to add:
- transactional fixtures with shared connection
- truncation of changed tables only
- set bcrypt cost to 1 (see how this applies to devise)
- make this generator interactive (simple yes/no questions)

**Comment by madsheep** [comment]
add a readme, and i'm cool to merge it.

**Comment by wiktorschmidt** [comment]
nie ma jeszcze? :(

**Comment by madsheep** [comment]
there you go (was in todos btw)

**Comment by wiktorschmidt** [comment]
:hamster:

**Pull request merged**
